# environment.yml
# Configuration file for creating a Conda Environment with dependencies needed for pyRSD.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create --name classylss-docs -f environment.yml

name: classylss-docs

channels:
- defaults
- bccp
- astropy
- conda-forge

dependencies:
- python=3.6
- classylss
- runtests
- matplotlib
- numpydoc
- IPython
- pip
- pip:
  - nbsphinx
  - sphinx_bootstrap_theme
